[package]
name = "aescry"
version = "1.0.0-rc.1"
authors = ["Daniel P. Clark <6ftdan@gmail.com>"]
edition = "2021"
rust-version = "1.63"

description = "AES encryption and decryption, including the AES Crypt file format."
homepage = "https://github.com/danielpclark/aescry"
repository = "https://github.com/danielpclark/aescry"
documentation = "https://docs.rs/aescry"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["aes", "aescrypt", "crypto", "encryption", "sha256"]
categories = ["cryptography"]
exclude = [".github", "fuzz"]

[dependencies]
getrandom = { version = "0.3", features = ["std"] }

[dev-dependencies]
proptest = { version = "1", default-features = false, features = ["std"] }
